ACTIVITY_HEADERS = [
    "Activity ID",
    "Date (YYYY-MM-DD)",
    "Start Time (HH:MM)",
    "Activity Type",
    "Activity Name",
    "Distance (km)",
    "Duration (min)",
    "Avg Pace (min/km)",
    "Average Grade Adjusted Pace (min/km)",
    "Total Ascent (m)",
    "Total Descent (m)",
    "Feels Like Temperature (Celsius)",
    "Weather Condition",
    "Sustained Wind Speed (km/h)",
    "Avg HR (bpm)",
    "Max HR (bpm)",
    "Average Cadence (spm)",
    "Average Stride Length (m)",
    "Average Ground Contact Time (ms)",
    "Vertical Oscillation (cm)",
    "Aerobic Training Effect (0.0-5.0)",
    "Anaerobic Training Effect (0.0-5.0)",
    "Activity Training Load",
    "Avg Power (Watts)",
    "Max Power (Watts)",
    "Normalized Power (Watts)",
    "Estimated Sweat Loss (ml)",
    "Garmin Training Effect Label",
    "HR Zone 1 (min)",
    "HR Zone 2 (min)",
    "HR Zone 3 (min)",
    "HR Zone 4 (min)",
    "HR Zone 5 (min)",
    "Power Zone 1 (min)",
    "Power Zone 2 (min)",
    "Power Zone 3 (min)",
    "Power Zone 4 (min)",
    "Power Zone 5 (min)"
]
